### ISSUE TITLE
500 error, when register

### ISSUE THREAD

**Issue by CORPARU** [exonum/exonum#1020] opened 2018-10-30 10:09 UTC
use docker image: https://hub.docker.com/r/serhiioryshych/exonum-cryptocurrency-advanced-example/

System: 
4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux,  
processor: Intel(R) Core(TM) i3 CPU M 370  @ 2.40GHz

![2018-10-30 16-43-36](https://user-images.githubusercontent.com/28980346/47710919-f1709280-dc6e-11e8-9640-3bc12adfd700.png)
![2018-10-30 17-46-28](https://user-images.githubusercontent.com/28980346/47710879-d7cf4b00-dc6e-11e8-8f0f-50402d4fcd5b.png)
![2018-10-30 17-48-47](https://user-images.githubusercontent.com/28980346/47710880-d7cf4b00-dc6e-11e8-8c8c-5936ea10f6c5.png)
![2018-10-30 17-49-09](https://user-images.githubusercontent.com/28980346/47710882-d867e180-dc6e-11e8-85b1-c92dad66c3a9.png)
![2018-10-30 17-57-41](https://user-images.githubusercontent.com/28980346/47710883-d867e180-dc6e-11e8-836c-e5702ac903c2.png)

**Comment by vitvakatu** [comment] 2018-10-30 10:17
Hello @CORPARU, thank you for creating an issue

Could you provide an output of your `docker exec <your_image> cat /proc/cpuinfo` command? You should run it after starting cryptocurrency-advanced docker image.

**Comment by CORPARU** [comment] 2018-10-30 10:34
still log file 
![2018-10-30 18-34-09](https://user-images.githubusercontent.com/28980346/47712354-790bd080-dc72-11e8-9427-b3473a0dabe1.png)

**Comment by CORPARU** [comment] 2018-10-30 11:16
fixed "launch.sh" end file line "cd ../../frontend" на "cd /usr/src/exonum/examples/cryptocurrency-advanced/frontend" and get result: 

![2018-10-30 18-58-38](https://user-images.githubusercontent.com/28980346/47714544-1ae1ec00-dc78-11e8-898e-69bd4787de09.png)

because is port 8008 busy

**Comment by atrykush** [comment] 2018-10-31 10:47
Hi
It looks like the cause of the issue is that the docker image was built for a different CPU family. Thus, some CPU instructions that are used by the built image couldn't be translated and understood by the system you're trying to start on.

**Comment by CORPARU** [comment] 2018-10-31 12:11
> Hi
> It looks like the cause of the issue is that the docker image was built for a different CPU family. Thus, some CPU instructions that are used by the built image couldn't be translated and understood by the system you're trying to start on.

yes thanks, I already understood it, I will collect in manual. I published more errors later, it looks like the directory addresses are incorrect

**Comment by aleksuss** [comment] 2018-10-31 12:38
@CORPARU could you close the issue please ?

**Closed** 2018-11-01 00:46 UTC
