### ISSUE TITLE
in cryptocurrency-advanced, program is generating to much empty blocks

### ISSUE THREAD

**Issue by AkezhanOb1** [exonum/exonum#912] opened 2018-08-28 04:59 UTC
I have built and opened cryptocurrency-advanced example, also made several transaction, and mentioned that the program generates too many empty blocks (I guess every second)

**Comment by aleksuss** [comment] 2018-08-28 06:12
@AkezhanOb1, this is the expected behavior of the program. We generate empty blocks even without transactions to show clients  that the program is still alive.

**Comment by vitvakatu** [comment] 2018-08-28 07:45
@ilammy what do you mean? You already can change amount of blocks per second using node configuration file. Disabling empty blocks completely will probably plummet our consensus safety. Although I thought a lot that current default timeout of 200 milliseconds is not realistic at all.
@AkezhanOb1 to read more about why we use empty blocks, please read [this post](https://exonum.com/blog/adjustable-timeouts-and-empty-blocks-2/).

If you have more questions, feel free to ask here or on our [Gitter](https://gitter.im/exonum/exonum). Otherwise I'm going to close this.

**Comment by vitvakatu** [comment] 2018-08-29 18:40
Closing due to lack of response. Feel free to create new issue if you have more questions.

**Closed by vitvakatu** 2018-08-29 18:40 UTC
